name: Autograding

on:
  push:
    branches:
      - main

jobs:
  testAPCalendar:
    name: Test APCalendar Class
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Gradle
      run: ./gradlew build -x test

    - name: Run APCalendar tests
      run: ./gradlew test --tests "com.example.APCalendarTest"

  testStepTracker:
    name: Test StepTracker Class
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
  
      - name: Build with Gradle
        run: ./gradlew build -x test
  
      - name: Run StepTracker tests
        run: ./gradlew test --tests "com.example.StepTrackerTest"

  testFuelDepot:
    name: Test FuelDepot Class
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
  
      - name: Build with Gradle
        run: ./gradlew build -x test
  
      - name: Run FuelDepot tests
        run: ./gradlew test --tests "com.example.FuelDepotTest"

  testSeatingChart:
    name: Test SeatingChart Class
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
  
      - name: Build with Gradle
        run: ./gradlew build -x test
  
      - name: Run SeatingChart tests
        run: ./gradlew test --tests "com.example.SeatingChartTest"

